[tool.poetry]
name = "syntax-robustness-nmt"
version = "0.1.0"
description = ""
authors = ["Atreya Shankar <35427332+atreyasha@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.6.10"
laserembeddings = "^1.0.1"
torch = "1.3.0"
ipython = "^7.15.0"
h5py = "^2.10.0"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
