[tool.poetry]
name = "syntax-paraphrasing-nmt"
version = "0.1.0"
description = ""
authors = ["Atreya Shankar <35427332+atreyasha@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.6"
attrdict = "2.0.1"
attrs = "19.1.0"
boto3 = "1.9.199"
botocore = "1.12.199"
certifi = "2019.6.16"
chardet = "3.0.4"
comet-git-pure = "0.19.11"
comet-ml = "2.0.5"
configobj = "5.0.6"
cycler = "0.10.0"
docutils = "0.14"
everett = "1.0.2"
idna = "2.8"
jmespath = "0.9.4"
joblib = "0.13.2"
jsonschema = "3.0.1"
kiwisolver = "1.1.0"
matplotlib = "3.1.1"
netifaces = "0.10.9"
numpy = "1.17.0"
nvidia-ml-py3 = "7.352.0"
pyparsing = "2.4.2"
pyrsistent = "0.15.4"
python-dateutil = "2.8.0"
transformers = "2.0.0"
regex = "2019.6.8"
requests = "2.22.0"
s3transfer = "0.2.1"
scipy = "1.3.0"
six = "1.12.0"
torch = "1.3.0"
tqdm = "4.32.2"
urllib3 = "1.25.3"
websocket-client = "0.56.0"
wurlitzer = "1.0.3"
gensim = "3.8.0"
zss = "1.2.0"
h5py = "2.10.0"
subword-nmt = "^0.3.7"
ipdb = "^0.13.2"
nltk = "3.4.5"
pillow = "6.2.2"
sacrebleu = "^1.4.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
